// ============================================================
// CONCEPT DATA - Generated from verticals.csv
// ============================================================

const CONCEPTS = [
  {
    id: 'healthcare-practice-banking',
    name: 'Healthcare Practice Banking',
    brandName: 'Lucrum',
    shortDesc: 'Banking that powers practice finances with modern checking, integrated billing, cash-flow tools, and specialized financing for healthcare practices.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop',
    tags: ['SMB', 'Healthcare', 'Payments', 'Deposits', 'Fee Income'],
    category: 'Healthcare, SMB, Professional Services',
    audienceType: 'SMB',
    growthObjective: 'Stable deposits, payments, billing, cash-flow management, fee income',
    launchModel: 'Standalone Brand; FI-Endorsed Vertical Solution',
    audience: 'Independent physician practices, dental practices, and healthcare operators managing reimbursements, payroll, patient payments, and recurring business expenses.',
    problem: 'Healthcare practices face administrative overhead, uneven reimbursement cycles, billing friction, and working-capital gaps traditional business banking rarely solves directly.',
    growthThesis: 'Gives an FI access to stable healthcare business deposits, payment volume, and fee-income opportunities while positioning the institution as a specialist partner for practice growth.',
    features: [
      'Practice-ready business checking',
      'Reimbursement cash-flow tracking',
      'Patient payment and billing tools',
      'Expense categorization by practice type',
      'Employee card controls by role',
      'Working capital and equipment financing',
      'Fast digital practice onboarding',
    ],
    goToMarket: [
      'Partner with physician and dental associations',
      'Target independent practices',
      'Offer as an endorsed practice banking solution',
      'Bundle payments, deposits, and financing',
    ],
    brandDirection: 'Professional, efficient, and clinically polished. Calm blues, clean typography, and practice-growth messaging.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Doctor, dentist, or practice owner reviewing finances in a modern clinic setting',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1G8ecYndIDem8byHXHgSK8Qf4zCiwwz0N/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1j8DDDZM4HrRUcHDIweb46BxxcNwG2nkn/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: '2025 Lucrum AtAGlance and Deck',
    relatedConcepts: ['professional-services-banking', 'construction-and-trades-banking']
  },
  {
    id: 'college-athlete-banking',
    name: 'College Athlete Banking',
    brandName: 'Athelite',
    shortDesc: 'A financial game plan for college athletes and fans, helping athletes manage NIL income, save for taxes, and connect fan banking with team support.',
    image: 'https://images.pexels.com/photos/264305/pexels-photo-264305.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    tags: ['Consumer', 'Sports', 'NIL', 'Younger Consumers', 'Affinity'],
    category: 'Sports, Consumer Affinity, Younger Consumers',
    audienceType: 'Consumer',
    growthObjective: 'Younger customers, deposits, fee income, affinity engagement',
    launchModel: 'Standalone Brand; College-Branded Offering',
    audience: 'College athletes earning NIL income, student athletes building financial independence, and highly engaged college sports fans.',
    problem: 'Student athletes have irregular income, tax obligations, brand deals, and limited financial education, while fans want more meaningful ways to support teams.',
    growthThesis: 'Creates a path to acquire young digital-native customers through sports affinity, NIL income management, fan engagement, deposits, and fee-income opportunities.',
    features: [
      'Student-friendly checking account',
      'Team-branded debit card',
      'NIL payment receipt and tracking',
      'Tax set-aside automation',
      'Brand deal income organization',
      'Athlete financial education modules',
      'Fan support and team roundups',
      'Fast mobile account opening',
    ],
    goToMarket: [
      'Launch direct to athletes and fans',
      'Partner with colleges',
      'Offer a college-branded version',
      'Use fan support mechanics to drive acquisition',
    ],
    brandDirection: 'Energetic, athletic, and confident. Bold sports imagery, strong typography, and community-driven storytelling.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'College athlete on campus or in training, paired with fan or team imagery',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/15KZRmEuROyshP22maYQ0UJ-58K3qoCDq/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1dzUBgU0E8pqFia8IQYyVVOneEgX3WKqC/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: '2025 Athelite AtAGlance and Deck',
    relatedConcepts: ['emerging-athlete-and-artist-wealth-banking', 'first-responder-banking']
  },
  {
    id: 'trucking-banking',
    name: 'Trucking Banking',
    brandName: 'Convoy',
    shortDesc: 'Banking built for life on the road, with mobile business banking, driver cards, invoice factoring, tax savings, forecasting, and asset-based finance.',
    image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&h=400&fit=crop',
    tags: ['SMB', 'Trucking', 'Logistics', 'Lending', 'Deposits'],
    category: 'Transportation, SMB, Logistics',
    audienceType: 'SMB',
    growthObjective: 'Business deposits, lending, invoice factoring, cash-flow management',
    launchModel: 'Standalone Brand; FI-Endorsed Vertical Solution',
    audience: 'Owner-operators, small trucking fleets, and transportation businesses managing fuel, maintenance, payroll, invoices, and working capital.',
    problem: 'Truckers face delayed payments, high operating expenses, fuel and maintenance volatility, tax complexity, and cash-flow pressure between loads.',
    growthThesis: 'Targets a cash-flow intensive SMB segment with deposit opportunity, factoring revenue, card spend, asset finance, and strong product relevance.',
    features: [
      'Mobile business checking for drivers',
      'Reserve savings for fuel and taxes',
      'Driver cards with spend controls',
      'Load, fuel, and maintenance categorization',
      'Invoice factoring and payment tracking',
      'Route-based spending forecasts',
      'Cash-balance visibility between loads',
      'Automated quarterly tax sweeps',
      'Truck and trailer financing access',
    ],
    goToMarket: [
      'Partner with trucking associations',
      'Target owner-operator communities',
      'Integrate with fuel, load board, or fleet partners',
      'Lead with invoice factoring',
    ],
    brandDirection: 'Rugged, practical, and mobile-first. Highway imagery, straight copy, and reliability-focused design.',
    complexity: 'Medium-High',
    launchTime: '5-7 months',
    imageDirection: 'Owner-operator beside a truck or reviewing payments from a cab',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1l6D2deej8Li-zfAvwfR0Z0Q_Tr4bDTnS/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1nsdyPG3sskNnG2t-Oeyy-K1uOWcfuH9q/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: '2025 Convoy AtAGlance and Deck',
    relatedConcepts: ['healthcare-practice-banking', 'construction-and-trades-banking']
  },
  {
    id: 'construction-and-trades-banking',
    name: 'Construction and Trades Banking',
    brandName: 'FRAME',
    shortDesc: 'Banking for builders, with project-based financials, streamlined invoices, trade payments, crew card controls, and cash-flow visibility.',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop',
    tags: ['SMB', 'Construction', 'Trades', 'Deposits', 'Fee Income'],
    category: 'Construction, Trades, SMB',
    audienceType: 'SMB',
    growthObjective: 'Sticky business deposits, next-gen SMB acquisition, fee income',
    launchModel: 'FI-Endorsed Vertical Solution; Product Line Under Existing Brand',
    audience: 'Construction employer businesses, self-employed contractors, tradespeople, and builders managing project cash flow, crews, suppliers, and job-based expenses.',
    problem: 'Builders need banking that reflects project-based work, fast supplier payments, crew-level spending controls, and real-time visibility into margins and cash flow.',
    growthThesis: 'Creates a targeted SMB banking wedge into a large construction segment with sticky operating deposits and strong fee-income potential.',
    features: [
      'Job-based account organization',
      'Project cash-flow and margin insights',
      'Trade and subcontractor payment tools',
      'Material supplier payment workflows',
      'Streamlined invoice creation and tracking',
      'Expense assignment by job or crew',
      'Business metrics for active projects',
      'Pro tools for growing contractors',
      'Crew card controls by site',
    ],
    goToMarket: [
      'Partner with contractor associations',
      'Target regional builders and trades',
      'Offer as contractor banking inside the FI business suite',
      'Lead with project cash-flow tooling',
    ],
    brandDirection: 'Confident, hard-working, and modern. Construction site imagery, strong layouts, and practical product visuals.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Contractor, builder, or construction worker reviewing project financials on site',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1t9Q5b50HGraz6804bjKOAI_9YuB6yu2i/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1ZFuwbPwOMVf8kZ4Rf6Fnq-3eRZeZbe4V/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: '2025 FRAME AtAGlance and Deck',
    relatedConcepts: ['landscaper-banking', 'healthcare-practice-banking']
  },
  {
    id: 'professional-services-banking',
    name: 'Professional Services Banking',
    brandName: 'SYSTM',
    shortDesc: 'A financial system for professional services growth, with invoicing, contractor payments, expense tracking, pro tools, employee controls, and capital access.',
    image: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=600&h=400&fit=crop',
    tags: ['SMB', 'Professional Services', 'Invoicing', 'Deposits', 'Fee Income'],
    category: 'Professional Services, SMB',
    audienceType: 'SMB',
    growthObjective: 'Business deposits, balance sheet diversification, fee income',
    launchModel: 'Standalone Brand; FI-Endorsed Vertical Solution',
    audience: 'Self-employed professionals and professional services firms that invoice clients, pay contractors, manage expenses, and need simple business-growth tools.',
    problem: 'Professional services businesses often stitch together separate tools for banking, invoicing, contractors, expenses, reporting, and working capital.',
    growthThesis: 'Positions an FI to acquire digitally active SMBs with operating deposits, payment activity, subscription potential, and capital needs.',
    features: [
      'Modern operating account for firms',
      'Business debit card controls',
      'Client invoicing and payment tracking',
      'Contractor payment workflows',
      'Vendor payment organization',
      'Expense assignment by client or project',
      'Revenue and cash-flow metrics',
      'Pro tools for growing firms',
      'Employee spend controls',
      'Capital access for growth needs',
    ],
    goToMarket: [
      'Target professional services verticals',
      'Partner with accountant and freelancer ecosystems',
      'Offer as endorsed SMB operating account',
      'Use invoicing and contractor payments as hooks',
    ],
    brandDirection: 'Modern, precise, and business-focused. Founder imagery, dashboards, and growth-system language.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Consultant, agency owner, or professional services founder working from a modern office',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1Krd1LiUQ1WuNRN3L1Vd0ATrOvoNdGx91/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1KuTE8KnqNGwkh739yj3zG4jbb1Zf1q4Q/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: '2025 SYSTM AtAGlance and Deck',
    relatedConcepts: ['healthcare-practice-banking', 'construction-and-trades-banking']
  },
  {
    id: 'family-and-youth-banking',
    name: 'Family and Youth Banking',
    brandName: 'Scurry',
    shortDesc: 'Smart family banking for kids and teens, with allowances, rewards, savings goals, roundups, investing education, and real-time parental controls.',
    image: 'https://images.unsplash.com/photo-1536640712-4d4c36ff0e4e?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Family', 'Kids', 'Teens', 'Education'],
    category: 'Family Banking, Youth Banking, Financial Education',
    audienceType: 'Consumer',
    growthObjective: 'Younger customers, family deposits, financial education, long-term loyalty',
    launchModel: 'Standalone Brand; Product Line Under Existing Brand',
    audience: 'Parents seeking safe, educational money tools for kids and teens, with family members able to support savings and financial learning.',
    problem: 'Families need a secure way to teach money habits, automate allowances, build savings, and manage youth spending with guardrails.',
    growthThesis: 'Creates early-life customer acquisition, household deposit growth, multi-generational relationships, and a compelling family banking product line.',
    features: [
      'Smart debit for kids and teens',
      'Allowance scheduling and transfers',
      'Chore-based reward tracking',
      'Learning-based savings incentives',
      'Savings goals for kids and families',
      'Family savings matching tools',
      'Purchase roundups into goals',
      'Age-appropriate investing education',
      'Real-time parental controls',
    ],
    goToMarket: [
      'Offer as a family banking product line',
      'Market to existing households',
      'Partner with schools and youth organizations',
      'Position as financial education',
    ],
    brandDirection: 'Trustworthy, warm, and family-friendly without feeling childish. Parent-child imagery and approachable design.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Parent and child reviewing savings goals or teen using a debit card responsibly',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1DswaxaurLgLi6sYScf8tJ42lKNHWW71K/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1KjSVn2GgY1Mbyab_SHkvZZ-RHOH7opRg/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: '2025 Scurry AtAGlance and Deck',
    relatedConcepts: ['k-12-education-banking', 'college-athlete-banking']
  },
  {
    id: 'agriculture-banking',
    name: 'Agriculture Banking',
    brandName: 'Prospr',
    shortDesc: 'Banking for the future of agriculture, with business banking, capital access, payroll, payments, savings sweeps, and ag-specific support.',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&h=400&fit=crop',
    tags: ['SMB', 'Agriculture', 'Equipment Finance', 'Deposits', 'Payments'],
    category: 'Agriculture, SMB',
    audienceType: 'SMB',
    growthObjective: 'Business deposits, equipment lending, payroll, payments, savings',
    launchModel: 'Standalone Brand; FI-Endorsed Vertical Solution',
    audience: 'Farm operators and agriculture businesses managing seasonal cash flow, equipment purchases, land costs, payroll, suppliers, and operating expenses.',
    problem: 'Agriculture businesses need banking that understands seasonality, equipment and land financing, payroll, payments, and ag operating cycles.',
    growthThesis: 'Helps an FI pursue agriculture operating deposits, lending relationships, and specialist advisory positioning in a relationship-heavy market.',
    features: [
      'Personal banking for farm households',
      'Business banking for farm operations',
      'Equipment financing pre-qualification',
      'Land and property financing support',
      'Seasonal operating capital access',
      'Vendor and buyer payment tools',
      'Payroll support for farm labor',
      'Automated reserve savings sweeps',
      'Ag-focused business support workflows',
      'Pro invoicing for farm sales',
    ],
    goToMarket: [
      'Target ag-heavy geographies',
      'Partner with grower associations and ag vendors',
      'Offer as FI-endorsed ag banking',
      'Bundle financing, deposits, and payroll',
    ],
    brandDirection: 'Grounded, optimistic, and practical. Modern agriculture imagery and language around resilience, growth, and operating confidence.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Farmer or ag business owner in field, barn, or equipment setting using mobile banking',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1FFotFV2LINGDGkVVgp7UttwORC_CDuMY/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1p4jkZvtsb9AzLVMEDItu2B8ZQQOEX9ri/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'Prospr AtAGlance and Deck',
    relatedConcepts: ['healthcare-practice-banking', 'trucking-banking']
  },
  {
    id: 'maker-and-artisan-banking',
    name: 'Maker and Artisan Banking',
    brandName: 'Métier',
    shortDesc: 'Banking for makers, with artisan checking, expense folders, cash-flow analytics, supplier payments, tax automation, and micro-loans.',
    image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=600&h=400&fit=crop',
    tags: ['SMB', 'Makers', 'Creator Economy', 'E-commerce', 'Deposits'],
    category: 'Creator Economy, SMB, Makers',
    audienceType: 'SMB',
    growthObjective: 'SMB deposits, lending, cash-flow tools, payments',
    launchModel: 'Standalone Brand; FI-Endorsed Vertical Solution',
    audience: 'Makers and artisans selling through marketplaces, direct channels, craft events, or online stores while managing inventory, sales, supplies, and taxes.',
    problem: 'Makers often mix personal and business finances and lack simple tools for expenses, inventory, supplier payments, tax reserves, and growth financing.',
    growthThesis: 'Provides a niche SMB acquisition path into creative commerce, with operating deposits, payments, fee income, and micro-lending potential.',
    features: [
      'Artisan business checking',
      'Savings accounts for materials and taxes',
      'Virtual folders for product expenses',
      'Cash-flow analytics for sales cycles',
      'Micro-loans for inventory growth',
      'Lines of credit for large orders',
      'Inventory and material expense tracking',
      'Supplier and marketplace payment tools',
      'Tax categorization for seller expenses',
      'Automated tax set-aside transfers',
    ],
    goToMarket: [
      'Partner with maker marketplaces and communities',
      'Target Etsy sellers and craft businesses',
      'Offer as creator SMB banking',
      'Use inventory and tax tools as the hook',
    ],
    brandDirection: 'Creative, handcrafted, and entrepreneurial. Maker studio imagery, tactile visuals, and copy around scaling a creative business.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Artisan or maker in studio packaging products or managing online sales',
    sourceAssetTypes: 'AtAGlance; Deck; Teaser',
    ataglanceUrl: 'https://drive.google.com/file/d/17qB-CLHwGhnAs8O4dHItL4oz1ccKjiKX/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1yu1RItESNeSDe58k7uK5aWSM4xVnACgC/view?usp=drivesdk',
    teaserUrl: 'https://drive.google.com/file/d/1MLx6OF6qx_wrKmRDWuAny--9XgIWqYHn/view?usp=drivesdk',
    sourceNotes: 'Métier AtAGlance, Deck, Teaser',
    relatedConcepts: ['healthcare-practice-banking', 'trucking-banking']
  },
  {
    id: 'life-sciences-banking',
    name: 'Life Sciences Banking',
    brandName: 'Luminary',
    shortDesc: 'A financial operating system for life sciences, designed to manage clinical trial finances, reduce costs, improve cash flow, and streamline reporting.',
    image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&h=400&fit=crop',
    tags: ['Commercial', 'Life Sciences', 'Healthcare', 'Treasury'],
    category: 'Life Sciences, Commercial, Healthcare',
    audienceType: 'Commercial',
    growthObjective: 'Treasury efficiency, cash-flow management, reporting, specialized operations',
    launchModel: 'Product Line Under Existing Brand; FI-Endorsed Vertical Solution',
    audience: 'Life sciences companies, clinical trial sponsors, and operators coordinating complex financial flows across research programs and trial sites.',
    problem: 'Clinical trial finances are operationally complex, with cost controls, cash-flow timing, reporting, and multi-party payment management creating friction.',
    growthThesis: 'Offers a specialized commercial banking wedge into a complex healthcare-adjacent vertical with high-value treasury and payments potential.',
    features: [
      'Clinical trial financial management',
      'Program-level cost control workflows',
      'Cash-flow visibility across trials',
      'Financial reporting support for sponsors',
      'Multi-party payment coordination',
      'Treasury dashboards for research operations',
    ],
    goToMarket: [
      'Target life sciences clusters',
      'Partner with clinical trial administrators',
      'Offer as commercial treasury specialization',
      'Position around trial finance efficiency',
    ],
    brandDirection: 'Scientific, precise, and high-trust. Lab, research, and life-sciences imagery with enterprise-grade design.',
    complexity: 'High',
    launchTime: '6-9 months',
    imageDirection: 'Life sciences team, lab environment, or clinical research finance context',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1vIp5F4ZWgWXcenN-WZV2dW1_lMY5ZHmp/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1hoemkyoI4z2Tfbq4y4o-oVK8e26ramw-/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'Luminary AtAGlance and Deck',
    relatedConcepts: ['healthcare-practice-banking', 'college-athlete-banking']
  },
  {
    id: 'remittance-and-newcomer-family-banking',
    name: 'Remittance and Newcomer Family Banking',
    brandName: 'Remesa',
    shortDesc: 'Better banking for building a better life, with debit, low-cost international transfers, early wage access, spending management, and savings roundups.',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Multicultural', 'Remittance', 'Inclusion'],
    category: 'Multicultural, Remittance, Consumer',
    audienceType: 'Consumer',
    growthObjective: 'Deposits, direct deposit, remittance relationships, financial inclusion',
    launchModel: 'Standalone Brand; FI-Endorsed Solution',
    audience: 'Consumers supporting family across borders, managing wages, everyday spending, transfers, and savings while building financial stability.',
    problem: 'Cross-border families need low-cost money movement, trusted everyday banking, early wage access, spending visibility, and support that understands family obligations.',
    growthThesis: 'Creates deposit, interchange, remittance, and loyalty opportunities through a culturally relevant, high-need consumer segment.',
    features: [
      'Modern debit card for everyday banking',
      'Fee-free ATM access where available',
      'Low-cost international transfer access',
      'Spending tracking for household budgets',
      'Early wage access with direct deposit',
      'Debit roundups into family savings',
      'Family-oriented support and onboarding',
    ],
    goToMarket: [
      'Partner with community organizations',
      'Target payroll and direct deposit users',
      'Offer remittance-led onboarding',
      'Build trust through family and goals',
    ],
    brandDirection: 'Warm, human, and family-centered. Multicultural family imagery and language around building a better life.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Multigenerational family, worker sending money home, or mobile transfer moment',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/183PdEe4Jlqs7iq-QeIsbHEq2g2bBiJ6Q/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1rZ_zcXpDbukhiXMXAtyzQd1INr-rXE-9/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'Remesa AtAGlance and Deck',
    relatedConcepts: ['newcomer-banking', 'rv-lifestyle-banking']
  },
  {
    id: 'emerging-athlete-and-artist-wealth-banking',
    name: 'Emerging Athlete and Artist Wealth Banking',
    brandName: 'SEMA',
    shortDesc: 'Exclusive banking for emerging athletes and artists, with premium cards, cashback, property financing, financial education, wealth management, and advisor support.',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Athletes', 'Artists', 'Wealth', 'Premium'],
    category: 'Talent, Wealth, Consumer Affinity',
    audienceType: 'Consumer',
    growthObjective: 'Affluent deposits, lending, wealth management, card spend',
    launchModel: 'Standalone Premium Vertical',
    audience: 'Emerging professional athletes and artists beginning to earn significant income while needing education, advice, lending, and wealth guidance.',
    problem: 'Early-career talent often faces sudden income, high purchase needs, financial complexity, and limited access to trusted specialist guidance.',
    growthThesis: 'Enables premium relationship banking with high-income affinity segments through cards, lending, deposits, and wealth advisory.',
    features: [
      'Premium debit card for everyday spend',
      'Premium credit card access',
      'Cashback on lifestyle spending',
      'High-yield savings for large income swings',
      'Property financing support',
      'Dedicated lending specialist access',
      'Financial education for sudden income',
      'Digital wealth management access',
      'Specialist advisor support for talent',
    ],
    goToMarket: [
      'Partner with agents, talent programs, artist networks, and athlete development groups',
      'Offer premium banking for emerging talent',
      'Use education and advisor access as trust hooks',
    ],
    brandDirection: 'Premium, aspirational, and protective. Talent and performance imagery with private-banking cues.',
    complexity: 'Medium-High',
    launchTime: '5-7 months',
    imageDirection: 'Emerging athlete, artist, or performer in a professional moment',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1ZiarHrM7oB79xPCv8UNbNgtKye61DkW_/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1tMrltVUu18AskvIwGwkMn6jJbgtkDJMu/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'SEMA AtAGlance and Deck',
    relatedConcepts: ['first-responder-banking', 'college-athlete-banking']
  },
  {
    id: 'rv-lifestyle-banking',
    name: 'RV Lifestyle Banking',
    brandName: 'Mirage',
    shortDesc: 'A nimble banking resource for the mobile RV life, with purchase and repair financing, budget tools, savings goals, RV-specific advisors, and charitable roundups.',
    image: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=600&h=400&fit=crop',
    tags: ['Consumer', 'RV', 'Recreation', 'Lending', 'Lifestyle'],
    category: 'Lifestyle, Recreation, Consumer',
    audienceType: 'Consumer',
    growthObjective: 'Lending, deposits, affluent affinity, rewards',
    launchModel: 'Standalone Brand; Affinity Partner Solution',
    audience: 'RV owners, mobile lifestyle consumers, retirees, travelers, and RV-adjacent small business owners.',
    problem: 'RV owners need capital for purchases or repairs, trip and lifestyle budgeting, savings goals, and advisors who understand mobile living.',
    growthThesis: 'Targets a passionate lifestyle segment with lending, deposits, card usage, rewards, and partner-led acquisition potential.',
    features: [
      'Purchase and emergency repair financing',
      'Trip and lifestyle expense planning',
      'Mobile budget tracking for RV life',
      'Goal-based savings for upgrades',
      'RV-specific financial advisor access',
      'Fee-free ATM benefits on the road',
      'Charity roundups for travel causes',
    ],
    goToMarket: [
      'Partner with RV clubs and dealers',
      'Target RV purchase and repair financing',
      'Offer as an affinity digital bank',
      'Use adventure savings and repair financing as hooks',
    ],
    brandDirection: 'Freedom-oriented, adventurous, and reassuring. Open-road visuals and confidence around planning.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'RV owner, mobile traveler, or family at an RV campsite using mobile banking',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1EAVOnJVzs0eY4vbCLNpnfrgkW7KEh-8y/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1uOtlItFF-Kl4Nhet0SdebROrNFI2B0R9/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'Mirage AtAGlance and Deck',
    relatedConcepts: ['boat-owner-banking', 'outdoor-adventure-banking']
  },
  {
    id: 'values-driven-banking',
    name: 'Values-Driven Banking',
    brandName: 'Believe',
    shortDesc: 'A bank that aligns money with values through cashback to causes, recycled cards, matched donations, charity customization, and purpose-driven engagement.',
    image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Purpose', 'Impact', 'Giving', 'Sustainability'],
    category: 'Purpose-Driven Banking, Consumer, Impact',
    audienceType: 'Consumer',
    growthObjective: 'Deposits, card spend, brand differentiation, charitable engagement',
    launchModel: 'Standalone Affinity Brand',
    audience: 'Consumers who want everyday banking to support causes, charities, sustainability, and values-aligned spending.',
    problem: 'Values-driven consumers often cannot see a clear link between their banking behavior and the causes they care about.',
    growthThesis: 'Builds brand differentiation, card engagement, deposit relationships, and mission-led loyalty through purpose-based banking.',
    features: [
      'Cashback rewards directed to causes',
      'Recycled debit card option',
      'Roundup donations from everyday spend',
      'Donation matching campaign tools',
      'Custom charity selection experience',
      'Cause progress and impact tracking',
      'Mission-driven engagement prompts',
    ],
    goToMarket: [
      'Partner with nonprofit networks',
      'Target values-driven consumers',
      'Launch as purpose-led digital brand',
      'Use donation matching and cause customization as hooks',
    ],
    brandDirection: 'Optimistic, values-led, and modern. Cause, community, and sustainability imagery with transparent impact metrics.',
    complexity: 'Medium-Low',
    launchTime: '3-5 months',
    imageDirection: 'Consumer supporting a cause, volunteer community, or values-led purchase moment',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1ICzQoMivpIPhY9mikxqgWeaJGB-_5BMJ/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/189XlGbycKsmP9wcUd7drSbVHU43RJJvQ/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'Believe AtAGlance and Deck',
    relatedConcepts: ['survivor-safety-banking', 'remittance-and-newcomer-family-banking']
  },
  {
    id: 'veteran-entrepreneur-banking',
    name: 'Veteran Entrepreneur Banking',
    brandName: 'Fortus',
    shortDesc: 'Business banking for veteran entrepreneurs, with fair capital access, modern accounts, payments, merchant services, mentor support, and better rates tied to business development.',
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=600&h=400&fit=crop',
    tags: ['SMB', 'Veterans', 'Vetpreneurs', 'Lending', 'Mentorship'],
    category: 'Veteran Business, SMB, Inclusive Capital',
    audienceType: 'SMB',
    growthObjective: 'Business lending, deposits, mentorship, community impact',
    launchModel: 'Standalone Brand; CU-Endorsed Vertical',
    audience: 'Veteran business owners and entrepreneurs launching, funding, or growing small businesses.',
    problem: 'Veteran entrepreneurs need fair credit access, business banking, payments, mentorship, and support that recognizes their skills and business journey.',
    growthThesis: 'Serves a high-affinity SMB community with deposits, lending, payments, merchant services, and mission-driven differentiation.',
    features: [
      'Fair credit review for veteran founders',
      'Streamlined capital loan applications',
      'Business checking for veteran-owned firms',
      'Business savings for reserves and taxes',
      'Fast payments for customers and vendors',
      'Digital transfers for business operations',
      'Merchant services for accepting payments',
      'Veteran business mentor access',
      'Rate benefits tied to skill development',
    ],
    goToMarket: [
      'Partner with veteran business groups',
      'Target veteran-owned SMBs',
      'Offer through credit unions with veteran ties',
      'Use mentorship plus capital as the hook',
    ],
    brandDirection: 'Respectful, strong, and practical. Veteran entrepreneur imagery without overly militarized clichés.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Veteran entrepreneur in business setting with mentor or advisor support',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1ahql6jkmNjdxtpMO02ZMcy9Q3wqo1rY0/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1bUOF1uv2l5Um75n6GQ30fNet8Sp-rpd2/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'Fortus AtAGlance and Deck',
    relatedConcepts: ['trucking-banking', 'franchisee-banking']
  },
  {
    id: 'gig-worker-banking',
    name: 'Gig Worker Banking',
    brandName: 'GigMoney',
    shortDesc: 'Modern money management for gig workers, with earnings tracking, expense planning, tax savings automation, receipt capture, debit, and savings tools.',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Gig Economy', 'Freelancers', 'Tax Savings'],
    category: 'Gig Economy, Consumer, Independent Work',
    audienceType: 'Consumer',
    growthObjective: 'Deposits, tax savings, financial wellness, debit engagement',
    launchModel: 'Standalone Brand; FI-Endorsed Solution',
    audience: 'Gig workers and freelancers managing income from multiple platforms, variable schedules, taxes, receipts, and inconsistent cash flow.',
    problem: 'Gig workers need banking that separates income, tracks work-specific expenses, prepares for taxes, and smooths months when work is light.',
    growthThesis: 'Targets a fast-growing workforce segment with direct deposits, debit usage, savings balances, and financial wellness differentiation.',
    features: [
      'Savings and debit for gig income',
      'Gig-by-gig earnings organization',
      'Expense planning for variable work',
      'Savings roundups for slow periods',
      'Automated tax set-aside transfers',
      'Receipt capture for deductions',
      'Expense assignment by platform or job',
    ],
    goToMarket: [
      'Partner with gig platforms and worker communities',
      'Target freelancers through tax-season campaigns',
      'Offer as endorsed gig banking',
      'Use tax automation as the primary hook',
    ],
    brandDirection: 'Flexible, modern, and practical. Independent worker imagery and clear tools for variable-income life.',
    complexity: 'Medium-Low',
    launchTime: '3-5 months',
    imageDirection: 'Gig worker, rideshare driver, delivery worker, or freelancer managing income on mobile',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1IXpRqGam9Yp-FIIFnoqdIkHKARw_0ZhO/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1ozdB6YZcxJeFvXKmHiu_kYLwkpm5UNkU/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'GigMoney AtAGlance and Deck',
    relatedConcepts: ['remittance-and-newcomer-family-banking', 'rv-lifestyle-banking']
  },
  {
    id: 'franchisee-banking',
    name: 'Franchisee Banking',
    brandName: 'SeriesF',
    shortDesc: 'Banking for franchisees, with fast approvals, franchise fee assistance, flexible loan terms, operating lines of credit, and franchise community support.',
    image: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=600&h=400&fit=crop',
    tags: ['SMB', 'Franchise', 'Lending', 'Operating Credit'],
    category: 'Franchise Finance, SMB, Lending',
    audienceType: 'SMB',
    growthObjective: 'Lending, deposits, operating credit, franchise growth',
    launchModel: 'Product Line Under Existing Brand; Standalone SMB Vertical',
    audience: 'Current and prospective franchisees seeking funding, operating credit, community support, and banking built around franchise timelines.',
    problem: 'Franchisees need financing that aligns to franchise fees, opening schedules, operating needs, and business ramp-up periods.',
    growthThesis: 'Offers lending-led acquisition into a structured SMB segment with deposit and credit expansion potential.',
    features: [
      'Fast financing pre-approval workflows',
      'Fast closings for franchise timelines',
      'Flexible loan terms for ramp-up periods',
      'Franchise fee assistance',
      'Adjustable rate options',
      'Fixed rate loan options',
      'Operating lines of credit',
      'Franchise community and support hub',
    ],
    goToMarket: [
      'Partner with franchise systems and brokers',
      'Target franchisee lending needs',
      'Offer as specialized SMB finance product',
      'Use franchise fee assistance as the hook',
    ],
    brandDirection: 'Growth-oriented, structured, and entrepreneurial. Franchise operator imagery and clear financing pathways.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Franchise owner in restaurant, retail, or service business context',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1C_8QsM4RfH5HI9t_tQVzlHmHhHFFjw4z/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1CEw4PzEBPLTHAr1b2iWMjtX1J1u-R9rN/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'SeriesF AtAGlance and Deck',
    relatedConcepts: ['trucking-banking', 'veteran-entrepreneur-banking']
  },
  {
    id: 'first-responder-banking',
    name: 'First Responder Banking',
    brandName: 'BlueSYREN',
    shortDesc: 'Banking that puts first responders first, with rewards, savings tools, specialist support, wealth guidance, and resilience education.',
    image: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=600&h=400&fit=crop',
    tags: ['Consumer', 'First Responders', 'Public Service', 'Wealth', 'Wellness'],
    category: 'Public Service, Consumer Affinity',
    audienceType: 'Consumer',
    growthObjective: 'Deposits, wealth, financial wellness, affinity loyalty',
    launchModel: 'Standalone Brand; CU-Endorsed Affinity Brand',
    audience: 'First responders and families managing demanding work, family financial goals, savings needs, and long-term planning.',
    problem: 'First responders need trusted financial tools and support tailored to high-stress public service careers and family stability.',
    growthThesis: 'Creates loyalty with a respected affinity community through deposit accounts, wealth support, rewards, and differentiated service.',
    features: [
      'Savings accounts for family goals',
      'Debit accounts for everyday banking',
      'Built-in rewards for service members',
      'Goal visualization for future planning',
      'Spending tracking for household budgets',
      'Specialist support agent access',
      'Wealth guidance for long-term security',
      'Mental resilience education resources',
      'Well-being courses and support content',
    ],
    goToMarket: [
      'Partner with first responder associations and unions',
      'Offer through community-focused CUs',
      'Use family security and specialist support as hooks',
    ],
    brandDirection: 'Respectful, protective, and calm. First responder imagery with family and future-planning cues.',
    complexity: 'Medium-Low',
    launchTime: '3-5 months',
    imageDirection: 'First responder with family, in uniform, or in community service context',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1IGeJ1x2Y4XEkbk9o4Zzr_HOgm18eYZEj/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1l4G1weSR6o-qEwVeU9IOuFTd-yI44oR0/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'BlueSYREN AtAGlance and Deck',
    relatedConcepts: ['emerging-athlete-and-artist-wealth-banking', 'college-athlete-banking']
  },
  {
    id: 'boat-owner-banking',
    name: 'Boat Owner Banking',
    brandName: 'Aboard',
    shortDesc: 'Bespoke banking for boat owners, with marina and fuel rewards, maintenance savings, boat finance, insurance, wealth services, and charter expense tracking.',
    image: 'https://images.pexels.com/photos/9770701/pexels-photo-9770701.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    tags: ['Consumer', 'Boating', 'Recreation', 'Lending', 'Wealth'],
    category: 'Boating, Affluent Recreation, Lifestyle',
    audienceType: 'Consumer',
    growthObjective: 'Lending, deposits, wealth, insurance, lifestyle rewards',
    launchModel: 'Standalone Brand; Affinity Partner Solution',
    audience: 'Boat owners, marina customers, charter operators, and affluent recreation consumers with financing, maintenance, insurance, and lifestyle spending needs.',
    problem: 'Boat owners need specialized financing, maintenance budgeting, marina rewards, insurance, wealth support, and expense tracking when chartering.',
    growthThesis: 'Targets an affluent passion segment with lending, deposits, card spend, insurance, wealth, and partner acquisition potential.',
    features: [
      'Fuel cashback at marine merchants',
      'Marina cashback and partner rewards',
      'Maintenance savings folders',
      'Boat insurance referral access',
      'Boat finance and refinance support',
      'Wealth management access',
      'Marina partner community offers',
      'Charter income tracking',
      'Charter expense tracking',
    ],
    goToMarket: [
      'Partner with marinas, boat dealers, and insurers',
      'Launch as boating affinity brand',
      'Use fuel and marina cashback as acquisition hook',
      'Bundle finance and insurance',
    ],
    brandDirection: 'Premium, coastal, and relaxed. Boat, marina, and affluent lifestyle imagery with understated luxury.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Boat owner at marina, on vessel, or reviewing expenses before a charter',
    sourceAssetTypes: 'AtAGlance; Deck; Teaser',
    ataglanceUrl: 'https://drive.google.com/file/d/1ExPINO8_5KO3aS__JAJmU9tUL5sVzC-8/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1EoOHfoc4bKneywvUatXQxArBqVv88ppJ/view?usp=drivesdk',
    teaserUrl: 'https://drive.google.com/file/d/1EfwQIL6BXODc1GKSllziWt9xwtWtZKXC/view?usp=drivesdk',
    sourceNotes: 'Aboard AtAGlance, Deck, Teaser',
    relatedConcepts: ['rv-lifestyle-banking', 'outdoor-adventure-banking']
  },
  {
    id: 'gamer-and-streamer-banking',
    name: 'Gamer and Streamer Banking',
    brandName: 'GAMR',
    shortDesc: 'High-performance banking for gamers and streamers, with gaming rewards, gear savings, fast account opening, streamer invoicing, and income tracking.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=400&fit=crop',
    tags: ['Consumer', 'SMB', 'Gaming', 'Streamers', 'Creator Economy'],
    category: 'Gaming, Creator Economy, Consumer and SMB',
    audienceType: 'Consumer and SMB',
    growthObjective: 'Younger customers, fee income, streamer SMB tools, deposits',
    launchModel: 'Standalone Brand; Creator-Economy Vertical',
    audience: 'Gamers, streamers, content creators, and gaming enthusiasts who spend on games and gear or earn income through streaming and sponsorships.',
    problem: 'Gamers want rewards and savings for gear, while streamers need business tools to manage sponsorship income, invoices, and creator revenue.',
    growthThesis: 'Captures younger consumers and creator SMBs through a high-affinity digital segment with deposits, fee income, card rewards, and premium tiers.',
    features: [
      'Checking and savings for gamers',
      'Gaming cashback and reward offers',
      'Gear savings goals',
      'Fast digital account opening',
      'Friends and family payment tools',
      'Early paycheck access with direct deposit',
      'Streamer invoicing tools',
      'Sponsorship and platform income tracking',
      'Premium tier for power users',
    ],
    goToMarket: [
      'Partner with gaming communities, streamers, and esports groups',
      'Offer consumer and streamer tiers',
      'Use gaming rewards and creator tools as hooks',
    ],
    brandDirection: 'High-energy, digital-native, and premium. Gaming visuals, creator setups, neon accents, and performance language.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Streamer at gaming setup, gamer with hardware, or esports community moment',
    sourceAssetTypes: 'Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1KDpPBmmlbzuZgaAGdvfVEzrAA2E49Pf1/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1KKuQu39VWRUHwphfudDv_S9XlcXrw11I/view?usp=drivesdk',
    teaserUrl: 'https://drive.google.com/file/d/1KKwP81eIXbDvv2RStT4_NBIhcfmko3O0/view?usp=drivesdk',
    sourceNotes: 'GAMR Deck',
    relatedConcepts: ['maker-and-artisan-banking', 'healthcare-practice-banking']
  },
  {
    id: 'landscaper-banking',
    name: 'Landscaper Banking',
    brandName: 'Verde',
    shortDesc: 'Banking for landscaping business growth, with project accounts, invoicing, equipment financing, crew payments, vendor payments, and tool integrations.',
    image: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=600&h=400&fit=crop',
    tags: ['SMB', 'Landscaping', 'Trades', 'Project Finance', 'Payments'],
    category: 'Landscaping, Trades, SMB',
    audienceType: 'SMB',
    growthObjective: 'Business deposits, project finance, payments, vendor and crew management',
    launchModel: 'Product Line Under Existing Brand; FI-Endorsed SMB Vertical',
    audience: 'Landscaping business owners and crews managing seasonal work, project budgets, equipment needs, vendor payments, and payroll.',
    problem: 'Landscaping SMBs face seasonal cash-flow swings, equipment financing needs, crew and vendor payments, and project-based expense tracking.',
    growthThesis: 'Creates a trades-focused SMB banking wedge with deposits, project finance, card usage, payments, and strong operational relevance.',
    features: [
      'Smart checking for landscaping businesses',
      'Project-based accounts by property or job',
      'Customer invoicing tools',
      'Recurring billing for maintenance contracts',
      'Equipment financing access',
      'Project financing for larger jobs',
      'Virtual cards for crew expenses',
      'Crew payment workflows',
      'Vendor and nursery payment tools',
      'Tool syncing with business workflows',
    ],
    goToMarket: [
      'Target landscaping businesses regionally',
      'Partner with equipment dealers and trade associations',
      'Offer as trades banking product line',
      'Lead with project finance and payments',
    ],
    brandDirection: 'Fresh, practical, and growth-oriented. Landscaping crew, equipment, and outdoor project imagery with green business cues.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Landscaper or crew owner on job site managing project payments',
    sourceAssetTypes: 'AtAGlance; Deck; Teaser',
    ataglanceUrl: 'https://drive.google.com/file/d/1IzGjMFjW1zzYWdvHdQIjIL_HIjykqbox/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1IuVp5r2kxeK0mgcjg5zzeY7X5OcXuFS3/view?usp=drivesdk',
    teaserUrl: 'https://drive.google.com/file/d/1ImIrRvYMGPK4Udp5UYkA5oRhgCltslFY/view?usp=drivesdk',
    sourceNotes: 'Verde AtAGlance, Deck, Teaser',
    relatedConcepts: ['construction-and-trades-banking', 'healthcare-practice-banking']
  },
  {
    id: 'k-12-education-banking',
    name: 'K-12 Education Banking',
    brandName: 'TeacherFi',
    shortDesc: 'Banking for a brighter future, with classroom goal folders, transparent donations, education cashback, college savings automation, and student participation.',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Education', 'Teachers', 'Family', 'Donations'],
    category: 'Education, Family Banking, Consumer Affinity',
    audienceType: 'Consumer',
    growthObjective: 'Family deposits, education savings, transparent donations, next-gen acquisition',
    launchModel: 'Standalone Brand; Licensed Family Banking Solution',
    audience: 'K-12 teachers, parents, students, and school communities seeking better ways to fund classroom needs, education savings, and student goals.',
    problem: 'Teachers and families face classroom funding gaps, rising education costs, limited transparency in donations, and fragmented college savings tools.',
    growthThesis: 'Creates family deposit growth, education affinity, next-generation acquisition, and community impact through classroom and college savings tools.',
    features: [
      'Classroom and learning goal folders',
      'Transparent classroom donation tracking',
      'College savings roundups',
      'Education cashback rewards',
      'Student voting on funded goals',
      'Grant assistance and application support',
      'Classroom incidentals funding tools',
    ],
    goToMarket: [
      'Partner with schools and parent communities',
      'Launch standalone or license to other FIs',
      'Market through classroom goals and college savings',
      'Use transparent donations as hook',
    ],
    brandDirection: 'Bright, trusted, and community-oriented. Classroom, family, and student imagery with optimistic education visuals.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Teacher, classroom, parent and student, or education savings moment',
    sourceAssetTypes: 'Deck',
    ataglanceUrl: '',
    deckUrl: 'https://drive.google.com/file/d/1FZ3nHd6fMt64-R3vquh3uSNTafop_Rs4/view?usp=drivesdk',
    teaserUrl: 'https://drive.google.com/file/d/1KxoZpBkqmGvtj8Q3sBqamNKiD5Ijdg0l/view?usp=drivesdk',
    sourceNotes: 'TeacherFi Deck',
    relatedConcepts: ['family-and-youth-banking', 'college-athlete-banking']
  },
  {
    id: 'workplace-financial-wellness-banking',
    name: 'Workplace Financial Wellness Banking',
    brandName: 'Employ',
    shortDesc: 'Workplace financial wellness banking with no minimums, no monthly fees, flexible contributions, direct deposit, ID theft protection, and portability.',
    image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Workplace', 'Payroll', 'Financial Wellness'],
    category: 'Workplace Banking, Financial Wellness',
    audienceType: 'Consumer',
    growthObjective: 'Payroll deposits, employee engagement, workplace wellness',
    launchModel: 'Product Line Under Existing Brand; Employer-Endorsed Solution',
    audience: 'Employees and employers seeking accessible, portable financial wellness tools linked to payroll and benefits.',
    problem: 'Workers need low-friction financial wellness tools that do not depend on employer administration and remain accessible after changing jobs.',
    growthThesis: 'Builds payroll deposit relationships and employer distribution while supporting financial wellness and portability.',
    features: [
      'No minimum balance account access',
      'No monthly fee banking',
      'Self-service contribution changes',
      'Automatic direct deposit setup',
      'No HR administration required',
      'ID theft protection support',
      'Portable account beyond employment',
    ],
    goToMarket: [
      'Partner with employers and benefits platforms',
      'Offer as workplace wellness product',
      'Target payroll deposit conversion',
      'Lead with portability and low-friction setup',
    ],
    brandDirection: 'Accessible, stable, and benefit-oriented. Workplace and employee wellness imagery with simple trust-building UI.',
    complexity: 'Medium-Low',
    launchTime: '3-5 months',
    imageDirection: 'Employee or workplace benefits moment, payroll and savings context',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: '',
    deckUrl: 'https://drive.google.com/file/d/1HYQY3NnKyOOguj2tk0StuZyOLhdvpOKr/view?usp=drivesdk',
    teaserUrl: '',
    sourceNotes: 'Employ AtAGlance and Deck',
    relatedConcepts: ['college-athlete-banking', 'family-and-youth-banking']
  },
  {
    id: 'survivor-safety-banking',
    name: 'Survivor Safety Banking',
    brandName: 'Vivien',
    shortDesc: 'Survivor-focused banking that helps users rebuild financial independence with safe accounts, debt support, credit rebuilding, alternative ID options, and wraparound resources.',
    image: 'https://images.pexels.com/photos/6383218/pexels-photo-6383218.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    tags: ['Consumer', 'Impact', 'Safety', 'Financial Inclusion', 'Survivor Support'],
    category: 'Impact, Safety Banking, Financial Inclusion',
    audienceType: 'Consumer',
    growthObjective: 'Social impact, financial independence, underserved market, lifelong loyalty',
    launchModel: 'Mission-Led Standalone Brand; FI-Endorsed Solution',
    audience: 'Survivors of domestic violence and financial abuse who need secure, low-cost banking, credit rebuilding, identity protection, and support services.',
    problem: 'Financial insecurity and financial abuse can prevent survivors from leaving unsafe situations and rebuilding long-term financial health.',
    growthThesis: 'Creates a values-driven impact brand that can reach an overlooked market, build lifelong loyalty, and align with corporate social responsibility goals.',
    features: [
      'Free checking with safe onboarding',
      'Secure debit card controls',
      'Prepaid card options for flexibility',
      'Debt consolidation support',
      'Structured repayment plan tools',
      'Credit score insights',
      'Credit rebuilding guidance',
      'Alternative ID support workflows',
      'Alternative address support workflows',
      'ID theft monitoring',
      'Savings roundups for independence',
      'Counseling resource connections',
      'Employment resource connections',
      'Housing resource connections',
    ],
    goToMarket: [
      'Mission-led digital brand',
      'Partner with survivor support organizations',
      'Offer through CSR-aligned FIs',
      'Prioritize safety, trust, and resource access',
    ],
    brandDirection: 'Calm, safe, empowering, and private. Respectful survivor-centered imagery, soft colors, and trust-forward language.',
    complexity: 'High',
    launchTime: '6-9 months',
    imageDirection: 'Empowered individual in safe, supportive setting, avoiding sensationalized crisis imagery',
    sourceAssetTypes: 'Teaser; Deck',
    ataglanceUrl: '',
    deckUrl: 'https://drive.google.com/file/d/1L4ajnIZkXTRhNPrGlpLePGRhWVFUrWvf/view?usp=drivesdk',
    teaserUrl: 'https://drive.google.com/file/d/1L6BKNVAcgHpQOOknKkxmSmMRL_zAUb3P/view?usp=drivesdk',
    sourceNotes: 'Vivien Teaser and Deck',
    relatedConcepts: ['values-driven-banking', 'newcomer-banking']
  },
  {
    id: 'newcomer-banking',
    name: 'Newcomer Banking',
    brandName: 'NewStart',
    shortDesc: 'Banking that simplifies a financial move, with U.S. account opening, debit, international transfers, credit-building support, bill tools, and job networking.',
    image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Newcomers', 'Immigrants', 'Credit Building', 'Inclusion'],
    category: 'Newcomer Banking, Multicultural, Financial Inclusion',
    audienceType: 'Consumer',
    growthObjective: 'Deposits, credit building, remittance, financial inclusion',
    launchModel: 'Standalone Brand; FI-Endorsed Solution',
    audience: 'Newcomers to the U.S. who need a bank account, debit card, credit-building support, transfers, housing or vehicle support, and work connections.',
    problem: 'New arrivals often lack local credit history and struggle with account access, transfers, housing, transportation, and the first steps of financial integration.',
    growthThesis: 'Builds early financial relationships with newcomer consumers through deposits, transfers, credit-building, and trusted support.',
    features: [
      'U.S. bank account opening support',
      'Visa debit card access',
      'Low-cost international transfer access',
      'Fast digital application',
      'Global financial history consideration',
      'Credit-building tips and education',
      'Spending tracking for new budgets',
      'Bill management and payment tools',
      'Rental support resources',
      'Vehicle support resources',
      'JobConnect networking support',
    ],
    goToMarket: [
      'Partner with newcomer organizations and employers',
      'Target relocation and immigrant communities',
      'Lead with credit-building and transfer support',
      'Offer as inclusive banking',
    ],
    brandDirection: 'Welcoming, practical, and optimistic. Relocation, family, and new-life imagery with clear support messaging.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Newcomer family, relocated professional, or account-opening moment',
    sourceAssetTypes: 'AtAGlance; Deck; Teaser',
    ataglanceUrl: 'https://drive.google.com/file/d/1IWQFm55vi0dFQFEaaOX_5erL9VkMNQ8Q/view?usp=drivesdk',
    deckUrl: 'https://drive.google.com/file/d/1IHS4ARMArspq6ad6qSzETzMpBq30ltcp/view?usp=drivesdk',
    teaserUrl: 'https://drive.google.com/file/d/1IMky-GiurEQgx0QQwrl_RuEh9uFV-T0Y/view?usp=drivesdk',
    sourceNotes: 'NewStart AtAGlance, Deck, Teaser',
    relatedConcepts: ['remittance-and-newcomer-family-banking', 'survivor-safety-banking']
  },
  {
    id: 'nurse-and-healthcare-worker-banking',
    name: 'Nurse and Healthcare Worker Banking',
    brandName: 'Praecuro',
    shortDesc: 'All-in-one banking for nurses to grow careers and wealth, with education financing, debt roundups, consolidated payments, financial wellness, and text-based advice.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Nurses', 'Healthcare Workers', 'Student Debt', 'Wealth'],
    category: 'Healthcare Workforce, Consumer, Career Banking',
    audienceType: 'Consumer',
    growthObjective: 'Student debt, career finance, deposits, wealth management',
    launchModel: 'Standalone Brand; Affinity Solution',
    audience: 'Nurses and healthcare workers managing education debt, career training, shift-based income, financial wellness, and long-term planning.',
    problem: 'Healthcare workers often carry education debt, need ongoing training financing, and have limited career-specific financial support.',
    growthThesis: 'Builds high-affinity consumer relationships with a stable workforce segment through debt support, deposits, education finance, and wealth services.',
    features: [
      'Academic debt roundup payments',
      'Affordable school financing access',
      'Training and certification financing',
      'Consolidated payment management',
      'Financial wellness support for shift workers',
      'Wealth management access',
      'Text-based financial advice',
    ],
    goToMarket: [
      'Partner with nursing associations, hospitals, and training programs',
      'Target early-career healthcare workers',
      'Use student debt support and career growth as hooks',
    ],
    brandDirection: 'Caring, professional, and supportive. Nurse and healthcare worker imagery with calm, trusted design.',
    complexity: 'Medium-Low',
    launchTime: '3-5 months',
    imageDirection: 'Nurse or healthcare worker in professional setting, financial wellness moment',
    sourceAssetTypes: 'AtAGlance; Deck',
    ataglanceUrl: 'https://drive.google.com/file/d/1G1Xf3UTaxGg_0d4gbRSS9OQ_LvHbzAux/view?usp=drivesdk',
    deckUrl: '',
    teaserUrl: '',
    sourceNotes: 'Praecuro AtAGlance and Deck',
    relatedConcepts: ['remittance-and-newcomer-family-banking', 'rv-lifestyle-banking']
  },
  {
    id: 'outdoor-adventure-banking',
    name: 'Outdoor Adventure Banking',
    brandName: 'Outbound',
    shortDesc: 'Banking for outdoor adventure enthusiasts, with gear and vehicle financing, trip budgeting, savings folders, carbon impact tracking, splitting, rewards, and green-cause roundups.',
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop',
    tags: ['Consumer', 'Outdoor', 'Recreation', 'Sustainability', 'Lending'],
    category: 'Outdoor Recreation, Lifestyle, Sustainability',
    audienceType: 'Consumer',
    growthObjective: 'Lending, deposits, sustainability, rewards, lifestyle affinity',
    launchModel: 'Standalone Affinity Brand',
    audience: 'Outdoor enthusiasts who spend on gear, trips, RVs, ATVs, boats, camping, hiking, and sustainability-minded recreation.',
    problem: 'Outdoor consumers need financing, budgeting, savings, transaction splitting, rewards, and environmental impact tools tied to their lifestyle.',
    growthThesis: 'Targets a large, passionate recreation segment with lending, deposits, card spend, rewards, and sustainability-led brand differentiation.',
    features: [
      'Gear financing for outdoor purchases',
      'Adventure vehicle financing access',
      'Emergency repair capital',
      'Trip expense planning',
      'Budget tracking for adventures',
      'Goal-based savings for gear and travel',
      'Carbon impact tracking',
      'Green retailer visibility',
      'Transaction splitting for group trips',
      'Gear cashback and rewards',
      'Green-cause roundups',
    ],
    goToMarket: [
      'Partner with outdoor brands, recreation clubs, and vehicle dealers',
      'Launch as adventure affinity bank',
      'Use financing, trip budgeting, and sustainability as hooks',
    ],
    brandDirection: 'Adventurous, sustainable, and modern. Outdoor landscapes, adventure gear, and clean environmental impact visuals.',
    complexity: 'Medium',
    launchTime: '4-6 months',
    imageDirection: 'Outdoor adventurer, camper, hiker, RV owner, or group splitting trip expenses',
    sourceAssetTypes: 'Teaser; Deck',
    ataglanceUrl: '',
    deckUrl: 'https://drive.google.com/file/d/1KUmmVCD0VKiwEiVhn65rod1wGRcDf90n/view?usp=drivesdk',
    teaserUrl: 'https://drive.google.com/file/d/1KbWR3sVlHYeJTC2ASq0v0Q4faTGR5xdi/view?usp=drivesdk',
    sourceNotes: 'Outbound Teaser and Deck',
    relatedConcepts: ['rv-lifestyle-banking', 'boat-owner-banking']
  }
];

// ============================================================
// WIZARD STEPS DATA
// ============================================================

const WIZARD_STEPS = [
  {
    id: 'growth-goal',
    question: 'What are you trying to grow?',
    subtitle: 'Select the primary growth objective for your institution.',
    options: [
      { id: 'deposits', label: 'Deposits', desc: 'Grow core deposits and reduce funding costs' },
      { id: 'fee-income', label: 'Fee Income', desc: 'Generate new non-interest revenue streams' },
      { id: 'lending', label: 'Lending', desc: 'Expand loan portfolio and credit products' },
      { id: 'smb-relationships', label: 'SMB Relationships', desc: 'Deepen small business engagement' },
      { id: 'younger-consumers', label: 'Younger Consumers', desc: 'Attract Gen Z and millennial customers' },
      { id: 'brand-differentiation', label: 'Brand Differentiation', desc: 'Stand out in a crowded market' }
    ]
  },
  {
    id: 'audience',
    question: 'Who are you trying to serve?',
    subtitle: 'Define the primary audience for your vertical banking concept.',
    options: [
      { id: 'consumers', label: 'Consumers', desc: 'Individual retail banking customers' },
      { id: 'small-businesses', label: 'Small Businesses', desc: 'Local and emerging business owners' },
      { id: 'commercial-verticals', label: 'Commercial Verticals', desc: 'Industry-specific commercial clients' },
      { id: 'affinity-communities', label: 'Affinity Communities', desc: 'Shared-interest or identity groups' },
      { id: 'existing-customers', label: 'Existing Customers', desc: 'Deepen relationships with current base' }
    ]
  },
  {
    id: 'go-to-market',
    question: 'How do you want to go to market?',
    subtitle: 'Choose the brand and launch model that fits your institution.',
    options: [
      { id: 'standalone-brand', label: 'Standalone Digital Brand', desc: 'A new brand identity, separate from your FI' },
      { id: 'endorsed-solution', label: 'FI-Endorsed Vertical Solution', desc: 'Your brand backing a specialized vertical' },
      { id: 'product-line', label: 'Product Line Under Existing Brand', desc: 'New products within your current brand' },
      { id: 'not-sure', label: 'Not Sure Yet', desc: 'Help me figure out the right model' }
    ]
  },
  {
    id: 'launch-posture',
    question: 'What is your launch posture?',
    subtitle: 'How do you want to approach the market entry?',
    options: [
      { id: 'test-learn', label: 'Test and Learn', desc: 'Start small, validate, then scale' },
      { id: 'fast-launch', label: 'Fast Launch', desc: 'Get to market quickly with an MVP' },
      { id: 'strategic-expansion', label: 'Strategic Expansion', desc: 'Methodical rollout with full planning' },
      { id: 'fully-differentiated', label: 'Fully Differentiated Brand', desc: 'Build a complete, standalone experience' }
    ]
  }
];

// ============================================================
// RECOMMENDATION LOGIC
// ============================================================

const RECOMMENDATION_MAP = {
  'deposits': ['healthcare-practice-banking', 'construction-and-trades-banking', 'agriculture-banking', 'trucking-banking'],
  'fee-income': ['professional-services-banking', 'life-sciences-banking', 'healthcare-practice-banking', 'franchisee-banking'],
  'lending': ['boat-owner-banking', 'rv-lifestyle-banking', 'outdoor-adventure-banking', 'franchisee-banking'],
  'smb-relationships': ['construction-and-trades-banking', 'professional-services-banking', 'landscaper-banking', 'veteran-entrepreneur-banking'],
  'younger-consumers': ['college-athlete-banking', 'gamer-and-streamer-banking', 'family-and-youth-banking', 'gig-worker-banking'],
  'brand-differentiation': ['values-driven-banking', 'emerging-athlete-and-artist-wealth-banking', 'survivor-safety-banking', 'first-responder-banking']
};

const RECOMMENDATION_REASONS = {
  'deposits': 'These concepts are optimized for deposit growth through high-velocity transaction accounts and recurring income capture from underserved segments.',
  'fee-income': 'These concepts generate fee income through specialized services, treasury management, and value-added tools that justify premium pricing.',
  'lending': 'These concepts open lending channels through asset financing, lifestyle purchases, and purpose-driven credit products.',
  'smb-relationships': 'These concepts deepen SMB relationships by solving real operational pain points that create daily engagement and switching costs.',
  'younger-consumers': 'These concepts resonate with younger demographics through modern brand identity, lifestyle alignment, and digital-first experiences.',
  'brand-differentiation': 'These concepts create strong market differentiation through bold brand positioning and unique audience alignment.'
};

// ============================================================
// BROWSE CATEGORIES
// ============================================================

const BROWSE_CATEGORIES = [
  { title: 'Featured Concepts', filter: () => true, limit: 9 },
  { title: 'Deposit Growth', filter: (c) => c.growthObjective.toLowerCase().includes('deposit') },
  { title: 'SMB & Commercial', filter: (c) => c.audienceType === 'SMB' || c.audienceType === 'Commercial' },
  { title: 'Consumer & Affinity', filter: (c) => c.audienceType === 'Consumer' || c.audienceType === 'Consumer and SMB' },
  { title: 'Lending & Finance', filter: (c) => c.growthObjective.toLowerCase().includes('lending') || c.growthObjective.toLowerCase().includes('finance') || c.tags.some(t => t.toLowerCase().includes('lending')) },
  { title: 'Lifestyle & Recreation', filter: (c) => c.category.toLowerCase().includes('lifestyle') || c.category.toLowerCase().includes('recreation') },
  { title: 'Fastest to Launch', filter: (c) => c.launchTime.includes('3-5') },
  { title: 'Purpose & Impact', filter: (c) => c.category.toLowerCase().includes('impact') || c.category.toLowerCase().includes('purpose') || c.category.toLowerCase().includes('inclusion') }
];
